#!/usr/bin/env node
/*
 * sync-web.js — bundle the SoA mobile client (/m/) into this Capacitor app.
 *
 * The native app is NOT a thin remote webview (that risks App Store 4.2
 * rejection): it ships the full web client inside the app bundle so the shell
 * loads offline, and only the live terminal stream needs the backend over the
 * network. This script copies web/public/m/* into ./www and injects a tiny
 * native-config script that tells the bundled client which backend to reach.
 *
 * Backend precedence at runtime (see app.js nativeBackend()):
 *   1. user override saved on-device (localStorage 'soa.native.backend')
 *   2. window.__SOA_BACKEND__  (baked below, from SOA_BACKEND env or default)
 *
 * Usage:  SOA_BACKEND="https://your-host" node scripts/sync-web.js
 */
const fs = require('fs');
const path = require('path');

const SRC = process.env.SOA_WEB_SRC || '/Users/test/.soa-web/web/public/m';
const DEST = path.join(__dirname, '..', 'www');
// Default backend: a public https/wss origin reachable from a real device AND
// the simulator. Override at sync time with SOA_BACKEND=... A trycloudflare
// quick-tunnel URL is ephemeral — set a stable tunnel for release builds.
const DEFAULT_BACKEND =
  process.env.SOA_BACKEND || 'https://gras-pest-harvard-arguments.trycloudflare.com';

function rmrf(p) {
  if (fs.existsSync(p)) fs.rmSync(p, { recursive: true, force: true });
}
function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

if (!fs.existsSync(SRC)) {
  console.error(`[sync-web] source not found: ${SRC}`);
  process.exit(1);
}

console.log(`[sync-web] bundling ${SRC} -> ${DEST}`);
rmrf(DEST);
copyDir(SRC, DEST);

// 1) native config script — sets window.__SOA_BACKEND__ before app.js runs.
const nativeCfg = `// AUTO-GENERATED by scripts/sync-web.js — do not edit by hand.
// Backend the bundled Son of Anton client connects to inside the native shell.
(function () {
  var DEFAULT_BACKEND = ${JSON.stringify(DEFAULT_BACKEND)};
  try {
    var override = localStorage.getItem('soa.native.backend');
    window.__SOA_BACKEND__ = (override && override.trim()) || DEFAULT_BACKEND;
  } catch (e) {
    window.__SOA_BACKEND__ = DEFAULT_BACKEND;
  }
  window.__SOA_NATIVE__ = true;
})();
`;
fs.writeFileSync(path.join(DEST, 'soa-native.js'), nativeCfg);

// 2) inject the config script BEFORE the app module in index.html.
const idxPath = path.join(DEST, 'index.html');
let html = fs.readFileSync(idxPath, 'utf8');
if (!html.includes('soa-native.js')) {
  html = html.replace(
    '<script type="module" src="app.js"></script>',
    '<script src="soa-native.js"></script>\n    <script type="module" src="app.js"></script>'
  );
  fs.writeFileSync(idxPath, html);
}

console.log(`[sync-web] backend = ${DEFAULT_BACKEND}`);
console.log('[sync-web] done.');
