#!/usr/bin/env bash
#
# Package the SoA mobile terminal client into a single portable archive that
# can be dropped into another project. Bundles every asset under web/public/m/
# (JS modules, CSS, HTML, service worker, PWA manifest, audio, icon) plus the
# PORTING.md protocol guide.
#
# Output: dist/soa-mobile-client.tar.gz  (and an unpacked copy in dist/)
#
# Usage:  bash scripts/package-mobile-client.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/web/public/m"
OUT="$ROOT/dist"
STAGE="$OUT/soa-mobile-client"
TARBALL="$OUT/soa-mobile-client.tar.gz"

[ -d "$SRC" ] || { echo "error: $SRC not found" >&2; exit 1; }

rm -rf "$STAGE" "$TARBALL"
mkdir -p "$STAGE"

# Copy the entire mobile client tree (assets + PORTING.md). Exclude editor cruft.
cp -R "$SRC/." "$STAGE/"
find "$STAGE" -name '.DS_Store' -delete 2>/dev/null || true

# A small manifest listing every shipped file with its size.
{
  echo "# soa-mobile-client — bundle manifest"
  echo "# generated by scripts/package-mobile-client.sh"
  echo
  ( cd "$STAGE" && find . -type f ! -name 'MANIFEST.txt' | sort | while read -r f; do
      sz=$(wc -c < "$f" | tr -d ' ')
      printf '%-40s %8s bytes\n' "${f#./}" "$sz"
  done )
} > "$STAGE/MANIFEST.txt"

# Single-file archive.
tar -C "$OUT" -czf "$TARBALL" "soa-mobile-client"

echo "Packaged mobile client:"
echo "  archive : $TARBALL"
echo "  unpacked: $STAGE/"
echo "  size    : $(wc -c < "$TARBALL" | tr -d ' ') bytes"
echo
echo "Files:"
sed -n '4,$p' "$STAGE/MANIFEST.txt" | sed 's/^/  /'
echo
echo "To replicate elsewhere: unpack, serve the folder over HTTP at /m/ (or"
echo "your root), and point it at a backend that speaks the protocol in"
echo "PORTING.md (GET /api/ping + WebSocket /ws with the JSON frame contract)."
