#!/usr/bin/env node
/**
 * Vercel build step.
 *
 * Rewrites web/public/_config.js so the deployed SPA knows how to behave.
 *
 * Env vars (set in Vercel project settings):
 *   SOA_WEB_MODE          'server' or 'webcontainer'. Default 'webcontainer'
 *                         on Vercel — there's no Node backend to talk to there.
 *   SOA_WEB_BACKEND       server-mode only: origin of the live backend.
 *   SOA_WEB_WC_CLIENT_ID  webcontainer-mode only: StackBlitz API key bound
 *                         to this deployment's origin.
 */

const fs = require('fs');
const path = require('path');

const mode = (process.env.SOA_WEB_MODE || 'webcontainer').toLowerCase();
const backend = (process.env.SOA_WEB_BACKEND || '').replace(/\/+$/, '');
const wcClientId = process.env.SOA_WEB_WC_CLIENT_ID || '';
const releaseUrl = process.env.SOA_WEB_RELEASE_URL || 'https://github.com/SimonSaysGiveMeSmile/SoA-Prod/releases';
const cfAnalyticsToken = process.env.SOA_WEB_CF_ANALYTICS_TOKEN || '';

const cfg = { mode, protocol: 1, backend, wcClientId, releaseUrl, cfAnalyticsToken };
const body = `/* generated by scripts/vercel-build.js */
window.__SOA_WEB__ = ${JSON.stringify(cfg, null, 2)};
`;

const target = path.resolve(__dirname, '../web/public/_config.js');
fs.writeFileSync(target, body);
console.log(`[soa-web] wrote ${target}`);
console.log(`[soa-web] mode=${mode} backend=${backend || '(same-origin)'} wcClientId=${wcClientId ? 'set' : '(unset)'} releaseUrl=${releaseUrl} cfAnalytics=${cfAnalyticsToken ? 'set' : '(unset)'}`);
