#!/usr/bin/env node
/**
 * Vercel build step.
 *
 * Rewrites web/public/_config.js so the deployed SPA knows which backend to
 * talk to. Controlled by two env vars set in the Vercel project settings:
 *   SOA_WEB_BACKEND — origin of the live backend (e.g. a Cloudflare Tunnel
 *                     URL like https://foo-bar-baz.trycloudflare.com). Empty
 *                     / unset → same-origin (default).
 *   SOA_WEB_AUTH    — 'shared' (default), 'open', or 'none'. Must match the
 *                     backend's SOA_WEB_AUTH so the login screen renders
 *                     correctly.
 *
 * Idempotent — run locally to preview the output file if you like.
 */

const fs = require('fs');
const path = require('path');

const backend = (process.env.SOA_WEB_BACKEND || '').replace(/\/+$/, '');
const authMode = process.env.SOA_WEB_AUTH || 'shared';

const cfg = { auth: authMode, protocol: 1, backend };
const body = `/* generated by scripts/vercel-build.js — do not commit */
window.__SOA_WEB__ = ${JSON.stringify(cfg, null, 2)};
`;

const target = path.resolve(__dirname, '../web/public/_config.js');
fs.writeFileSync(target, body);
console.log(`[soa-web] wrote ${target}`);
console.log(`[soa-web] backend=${backend || '(same-origin)'} auth=${authMode}`);
